[profile.default]
src = "."
out = "out"
libs = ["node_modules"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
bsc_testnet = "https://bsc-testnet.publicnode.com"
bsc_mainnet = "https://bsc-dataseed.binance.org"
